import cv2, numpy as np, matplotlib.pyplot as plt, os
img = cv2.imread(os.path.join(os.path.dirname(__file__), 'Cropped segment.png'), 0)
img = cv2.resize(img, None, fx=2, fy=2, interpolation=cv2.INTER_NEAREST)
edges = cv2.Canny(img, 550, 690)
indices = np.where(edges != 0)
x, y = indices[1], indices[0]
x_m, y_m = np.mean(x), np.mean(y)
pts = np.column_stack([x-x_m, y-y_m])
U, S, Vt = np.linalg.svd(pts, full_matrices=False)
m = Vt[0][1]/Vt[0][0] if Vt[0][0]!=0 else float('inf')
theta = np.degrees(np.arctan(m))
plt.figure(figsize=(14, 10), dpi=100)
plt.scatter(x, y, s=5, alpha=0.3)
x_line = np.array([x.min(), x.max()])
plt.plot(x_line, m*x_line+(y_m-m*x_m), 'b-', linewidth=3); plt.gca().invert_yaxis()
plt.title(f'Q6-Q7: Total Least Squares θ={theta:.2f}°', fontsize=14)
plt.savefig('Q6_Q7_TotalLeastSquares.png', dpi=150, bbox_inches='tight'); plt.show()
print(f'Slope:{m:.6f} θ:{theta:.2f}°')
